### PR TITLE
Add workflow default file support

### PR DESCRIPTION
**Pull request by mvdbeek**
Goes together with https://github.com/galaxyproject/galaxy/pull/13110/

### CODE REVIEW

**Comment by mr-c** [comment]
Does this need a schema update?

**Comment by mvdbeek** [comment]
It is already in the schema (http://galaxyproject.github.io/gxformat2/v19_09.html#WorkflowStepInput), but its type is `Any`. I'll add the mandatory keys.

**Comment by mvdbeek** [comment]
Hmm, `default` is `Any` in cwl as well (https://www.commonwl.org/v1.2/Workflow.html#WorkflowStepInput). And I guess that makes sense ? So maybe we don't need to do anything here for now ?

**Comment by mr-c** [comment]
@mvdbeek right; all good then!

**Review by jmchilton — APPROVED** [review]

**Pull request merged**
