### PR TITLE
Add typescript implementation

### PR DESCRIPTION
**Pull request by mr-c**
Courtesy of @ZimmerA 's https://github.com/common-workflow-language/schema_salad/pull/479

`schema-salad-tool --codegen=typescript --codegen-target typescript schema/v19_09/workflow.yml`

- [x] Add the command to build_schema.sh (after the schema_salad [PR](https://github.com/common-workflow-language/schema_salad/pull/479) is merged and released)
- [x] Run the example loading tests
- [ ] Other tests? (needs a TypeScript person)

### CODE REVIEW

**Comment by nsoranzo** [comment]
Add the command to `build_schema.sh` ?

**Comment by mr-c** [comment]
> Add the command to `build_schema.sh` ?

Yep, after the schema_salad PR is merged and released

**Comment by jmchilton** [comment]
Well that is fun. Are we targeting a use case or is this more speculative (I'm fine either way - just curious).

**Comment by bgruening** [comment]
@davelopez for the workflow integration in GLS :)

**Comment by davelopez** [comment]
Wow, this looks really interesting! I definitely want to explore creating a new extension for VSCode specific for Galaxy workflows that work directly on the browser (like in [github.dev](https://github.dev/github/dev)) and this seems like it could be extremely helpful :)

**Comment by mr-c** [comment]
@davelopez and the rest: what do you think would be the criteria for merging this?

(Beyond waiting for the origin PR to get merged and a new schema-salad release)

**Comment by mvdbeek** [comment]
I think we can merge this when you're happy with the changes @mr-c

**Comment by mr-c** [comment]
@zimmera Any thoughts about https://github.com/galaxyproject/gxformat2/runs/4691758835?check_suite_focus=true#step:6:14 ?

```
TSError: ⨯ Unable to compile TypeScript:
Error: src/GalaxyWorkflow.ts(102,63): error TS2693: 'string' only refers to a type, but is being used as a value here.
```

**Comment by ZimmerA** [comment]
> @ZimmerA Any thoughts about https://github.com/galaxyproject/gxformat2/runs/4691758835?check_suite_focus=true#step:6:14 ?
> 
> ```
> TSError: ⨯ Unable to compile TypeScript:
> Error: src/GalaxyWorkflow.ts(102,63): error TS2693: 'string' only refers to a type, but is being used as a value here.
> ```

I'll take a look!

**Comment by ZimmerA** [comment]
@mr-c https://github.com/common-workflow-language/schema_salad/pull/499/files contains a fix. Can you try if it works?

**Comment by mr-c** [comment]
@ZimmerA That worked, thanks!

**Comment by mr-c** [comment]
@mvdbeek @nsoranzo @davelopez @jmchilton This is ready for review and merging!

**Pull request merged**
